// AUTO-GENERATED from academic-advisor/data/courses.json + prerequisites.json.
// Do not edit by hand — regenerate with the generator script instead.

export interface CatalogCourse {
  code: string;
  name: string;
  credit_hours: number;
  group_type: string;
  departments: string[];
  prereqs: string[];
}

export const DEPARTMENT_LABELS: Record<string, string> = {
  ALL: "General",
  AI_GENERAL: "Artificial Intelligence",
  CYBER_SECURITY: "Cyber Security",
  BIO_INFORMATICS: "Bioinformatics",
};

export const CATALOG: CatalogCourse[] = [
  { code: "GEN001", name: "Information Technology", credit_hours: 2, group_type: "University Requirement", departments: ["ALL"], prereqs: [] },
  { code: "GEN002", name: "English (1)", credit_hours: 2, group_type: "University Requirement", departments: ["ALL"], prereqs: [] },
  { code: "GEN101", name: "English (2)", credit_hours: 2, group_type: "University Requirement", departments: ["ALL"], prereqs: ["GEN002"] },
  { code: "GEN003", name: "Psychology and Organization Behavior", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN004", name: "Modern Egyptian History", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN005", name: "Introduction to Law and Human Rights", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN102", name: "Leadership, Team Approach and Communications Skills", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN202", name: "Legislations, Contract and Procurement Management", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN302", name: "General Risk Management", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN303", name: "Project Management", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN401", name: "Marketing Skills", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN402", name: "Creativity and Critical Thinking", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "GEN403", name: "Introduction to Economics", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "BAS112", name: "Calculus", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: [] },
  { code: "BAS113", name: "Linear Algebra", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: [] },
  { code: "BAS114", name: "Physics", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: [] },
  { code: "BAS116", name: "Basic Electricity & Electronics", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: [] },
  { code: "BAS123", name: "Probability and Statistics", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: ["BAS113"] },
  { code: "BAS126", name: "Discrete Structures", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: ["BAS113"] },
  { code: "BAS211", name: "Numerical Computation", credit_hours: 2, group_type: "Basic Science", departments: ["ALL"], prereqs: ["BAS126"] },
  { code: "BAS212", name: "Operations Research", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: ["BAS123"] },
  { code: "BAS221", name: "Modeling and Simulation", credit_hours: 3, group_type: "Basic Science", departments: ["ALL"], prereqs: ["BAS211"] },
  { code: "CSC115", name: "Introduction to Computer Systems", credit_hours: 3, group_type: "Computer Science", departments: ["ALL"], prereqs: [] },
  { code: "CSC124", name: "Structural Programming", credit_hours: 3, group_type: "Computer Science", departments: ["ALL"], prereqs: ["CSC115"] },
  { code: "CSC125", name: "Database Management Systems", credit_hours: 3, group_type: "Computer Science", departments: ["ALL"], prereqs: ["CSC115"] },
  { code: "CSC213", name: "Data Mining and Exploration", credit_hours: 3, group_type: "Computer Science", departments: ["ALL"], prereqs: ["CSC125"] },
  { code: "CSC214", name: "Computer Networks and Data Communication", credit_hours: 3, group_type: "Computer Science", departments: ["ALL"], prereqs: ["CSC115"] },
  { code: "CSC222", name: "Computer Graphics and Vision", credit_hours: 3, group_type: "Computer Science", departments: ["ALL"], prereqs: ["CSC124", "BAS211"] },
  { code: "CSC223", name: "Computer Architecture", credit_hours: 3, group_type: "Computer Science", departments: ["ALL"], prereqs: ["CSC115"] },
  { code: "AI127", name: "Introduction to Artificial Intelligence", credit_hours: 3, group_type: "Mandatory AI", departments: ["ALL"], prereqs: ["CSC115"] },
  { code: "AI215", name: "Digital Logic Design", credit_hours: 3, group_type: "Mandatory AI", departments: ["ALL"], prereqs: ["BAS126", "AI127"] },
  { code: "AI216", name: "Machine Learning and Pattern Recognition", credit_hours: 3, group_type: "Mandatory AI", departments: ["ALL"], prereqs: ["AI127", "BAS123"] },
  { code: "AI224", name: "Artificial Intelligence Programming Languages", credit_hours: 3, group_type: "Mandatory AI", departments: ["ALL"], prereqs: ["CSC124", "AI127"] },
  { code: "AI225", name: "Processing Formal and Natural Languages", credit_hours: 3, group_type: "Mandatory AI", departments: ["ALL"], prereqs: ["AI215"] },
  { code: "CSC227", name: "Work-based Professional Project in Computer Science", credit_hours: 2, group_type: "Practical Project", departments: ["ALL"], prereqs: ["CSC124", "CSC125"] },
  { code: "CSC311", name: "Big Data Analytics", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["CSC213"] },
  { code: "CSC312", name: "Computer Security and Cryptography", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["CSC214", "BAS211"] },
  { code: "CSC313", name: "Data Structure and Algorithms", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["CSC124"] },
  { code: "AI314", name: "Agent Based Systems", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["BAS221"] },
  { code: "AI315", name: "Computational Cognitive Science", credit_hours: 3, group_type: "Major Core", departments: ["AI_GENERAL", "CYBER_SECURITY"], prereqs: ["BAS221"] },
  { code: "AI323", name: "Computational Neuroscience", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["AI216"] },
  { code: "AI324", name: "Automated Reasoning", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["AI314"] },
  { code: "AI325", name: "Human Computer Interaction", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["AI225"] },
  { code: "AI326", name: "Embedded Systems and Automation", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["AI314"] },
  { code: "CSC322", name: "Cloud Architecture and Computing", credit_hours: 3, group_type: "Major Core", departments: ["ALL"], prereqs: ["CSC223"] },
  { code: "AI424", name: "Deep Learning", credit_hours: 3, group_type: "Major Core", departments: ["AI_GENERAL", "CYBER_SECURITY"], prereqs: ["AI216"] },
  { code: "AI317", name: "Work-based Professional Project (I)", credit_hours: 1, group_type: "Major Core", departments: ["AI_GENERAL", "CYBER_SECURITY"], prereqs: ["AI225"] },
  { code: "AI327", name: "Work-based Professional Project (II)", credit_hours: 1, group_type: "Major Core", departments: ["AI_GENERAL", "CYBER_SECURITY"], prereqs: ["AI317"] },
  { code: "AI411", name: "Principles and Design of AI/IoT Systems", credit_hours: 3, group_type: "AI Major", departments: ["AI_GENERAL"], prereqs: ["AI216", "AI326"] },
  { code: "AI412", name: "Theory of Automata and Formal Languages", credit_hours: 3, group_type: "AI Major", departments: ["AI_GENERAL"], prereqs: ["BAS126"] },
  { code: "AI413", name: "Interactive Systems Design", credit_hours: 3, group_type: "AI Major", departments: ["AI_GENERAL"], prereqs: ["AI325"] },
  { code: "AI414", name: "Cyber-Physical Systems", credit_hours: 3, group_type: "AI Major", departments: ["AI_GENERAL", "CYBER_SECURITY"], prereqs: ["AI326", "CSC312"] },
  { code: "AI415", name: "Graduation Project in AI (I)", credit_hours: 2, group_type: "Graduation Project", departments: ["AI_GENERAL"], prereqs: ["AI327"] },
  { code: "AI421", name: "Data Center Virtualization", credit_hours: 3, group_type: "AI Major", departments: ["AI_GENERAL"], prereqs: ["CSC322"] },
  { code: "AI422", name: "Embedded and Real Time Operating Systems", credit_hours: 3, group_type: "AI Major", departments: ["AI_GENERAL"], prereqs: ["AI326"] },
  { code: "AI423", name: "Wireless Sensor Protocols and Programming", credit_hours: 3, group_type: "AI Major", departments: ["AI_GENERAL"], prereqs: ["AI314", "AI412"] },
  { code: "AI425", name: "Graduation Project in AI (II)", credit_hours: 2, group_type: "Graduation Project", departments: ["AI_GENERAL"], prereqs: ["AI415"] },
  { code: "AIE31", name: "Fog Computing", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["CSC322"] },
  { code: "AIE32", name: "Virtual Environment", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["AI411"] },
  { code: "SEC322", name: "Cyber Security Risk Management (AI Elective)", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["AI414"] },
  { code: "AIE431", name: "Cloud Storage Infrastructure", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["CSC322"] },
  { code: "AIE42", name: "Software Architecture and Interoperability", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["AI411", "CSC223"] },
  { code: "AIE44", name: "Cloud Strategy Planning and Management", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["CSC322"] },
  { code: "AIE45", name: "New Trends in IoT", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["CSC322"] },
  { code: "AIE46", name: "New Trends in AI", credit_hours: 3, group_type: "AI Elective", departments: ["AI_GENERAL"], prereqs: ["CSC322"] },
  { code: "SEC411", name: "Foundations of Cyber Security", credit_hours: 3, group_type: "Cyber Security Major", departments: ["CYBER_SECURITY"], prereqs: ["CSC312"] },
  { code: "SEC412", name: "Cyber Incident Response and Computer Network Forensics", credit_hours: 3, group_type: "Cyber Security Major", departments: ["CYBER_SECURITY"], prereqs: ["CSC312"] },
  { code: "SEC413", name: "Network Visualization and Vulnerability Detection", credit_hours: 3, group_type: "Cyber Security Major", departments: ["CYBER_SECURITY"], prereqs: ["CSC312"] },
  { code: "SEC415", name: "Graduation Project in Cyber Security (I)", credit_hours: 3, group_type: "Graduation Project", departments: ["CYBER_SECURITY"], prereqs: ["AI327"] },
  { code: "SEC421", name: "Secure Systems Architecture", credit_hours: 3, group_type: "Cyber Security Major", departments: ["CYBER_SECURITY"], prereqs: ["SEC411"] },
  { code: "SEC422", name: "Cyber Security Risk Management", credit_hours: 3, group_type: "Cyber Security Major", departments: ["CYBER_SECURITY"], prereqs: ["SEC411"] },
  { code: "SEC423", name: "Formal Verification of Reactive Systems", credit_hours: 3, group_type: "Cyber Security Major", departments: ["CYBER_SECURITY"], prereqs: ["SEC413"] },
  { code: "SEC424", name: "Digital Forensics", credit_hours: 3, group_type: "Cyber Security Major", departments: ["CYBER_SECURITY"], prereqs: ["SEC412"] },
  { code: "SEC425", name: "Graduation Project in Cyber Security (II)", credit_hours: 3, group_type: "Graduation Project", departments: ["CYBER_SECURITY"], prereqs: ["SEC415"] },
  { code: "SECE32", name: "Ethical Hacking", credit_hours: 3, group_type: "Cyber Security Elective", departments: ["CYBER_SECURITY"], prereqs: ["SEC412"] },
  { code: "SECE43", name: "Virtualization and Cloud Security", credit_hours: 3, group_type: "Cyber Security Elective", departments: ["CYBER_SECURITY"], prereqs: ["CSC322"] },
  { code: "SECE44", name: "Cyber Criminology", credit_hours: 3, group_type: "Cyber Security Elective", departments: ["CYBER_SECURITY"], prereqs: ["SEC411"] },
  { code: "SECE45", name: "Enterprise Security and Information Assurance", credit_hours: 3, group_type: "Cyber Security Elective", departments: ["CYBER_SECURITY"], prereqs: ["CSC312"] },
  { code: "SECE46", name: "Systems Administration and Network Services", credit_hours: 3, group_type: "Cyber Security Elective", departments: ["CYBER_SECURITY"], prereqs: ["CSC214"] },
  { code: "SECE47", name: "Cyber Intelligence", credit_hours: 3, group_type: "Cyber Security Elective", departments: ["CYBER_SECURITY"], prereqs: ["SEC412"] },
  { code: "SEC48", name: "New Trends on Cyber Security", credit_hours: 3, group_type: "Cyber Security Elective", departments: ["CYBER_SECURITY"], prereqs: ["SEC412"] },
  { code: "BIO312", name: "Introduction to Bioinformatics", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["CSC115"] },
  { code: "BIO314", name: "Biological Database", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["CSC125"] },
  { code: "BIO315", name: "Molecular and Cell Biology", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: [] },
  { code: "BIO316", name: "Work-based Professional Project in Bioinformatics (I)", credit_hours: 1, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["AI215"] },
  { code: "BIO321", name: "Basic and Population Genetics", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO315"] },
  { code: "BIO322", name: "Biochemistry", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO312"] },
  { code: "BIO324", name: "Bioinformatics Programming", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["CSC124"] },
  { code: "BIO325", name: "Computational Biology", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO315"] },
  { code: "BIO326", name: "Work-based Professional Project in Bioinformatics (II)", credit_hours: 1, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO316"] },
  { code: "BIO411", name: "Genetic Engineering", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO321"] },
  { code: "BIO412", name: "Biological Sequence Analysis", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO315"] },
  { code: "BIO413", name: "Genomics and Proteomics", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO315"] },
  { code: "BIO414", name: "Bio-mathematics", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO412"] },
  { code: "BIO415", name: "Graduation Project in Bioinformatics (I)", credit_hours: 3, group_type: "Graduation Project", departments: ["BIO_INFORMATICS"], prereqs: ["BIO325"] },
  { code: "BIO421", name: "Automation Solution in Bioinformatics", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["AI215", "BIO411"] },
  { code: "BIO422", name: "Computational Gene Finding and Genome Assembly", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO414"] },
  { code: "BIO423", name: "Biometrics", credit_hours: 3, group_type: "Bioinformatics Major", departments: ["BIO_INFORMATICS"], prereqs: ["BIO315"] },
  { code: "BIO425", name: "Graduation Project in Bioinformatics (II)", credit_hours: 3, group_type: "Graduation Project", departments: ["BIO_INFORMATICS"], prereqs: ["BIO415"] },
  { code: "BIOE31", name: "Methods and Applications of Molecular Modeling", credit_hours: 3, group_type: "Bioinformatics Elective", departments: ["BIO_INFORMATICS"], prereqs: ["BIO411"] },
  { code: "BIOE42", name: "Multicellular Life", credit_hours: 3, group_type: "Bioinformatics Elective", departments: ["BIO_INFORMATICS"], prereqs: ["BIO414"] },
  { code: "BIOE43", name: "Applied Genomic Technologies / Computational Molecular Biology", credit_hours: 3, group_type: "Bioinformatics Elective", departments: ["BIO_INFORMATICS"], prereqs: ["BIO414"] },
  { code: "BIOE44", name: "Recombinant DNA Techniques / Biometrics", credit_hours: 3, group_type: "Bioinformatics Elective", departments: ["BIO_INFORMATICS"], prereqs: ["BIO414"] },
  { code: "BIOE45", name: "Applied Biotechnology / Applied Genomic Technologies", credit_hours: 3, group_type: "Bioinformatics Elective", departments: ["BIO_INFORMATICS"], prereqs: ["BIO414"] },
  { code: "BIOE46", name: "New Trends in Bio-Informatics", credit_hours: 3, group_type: "Bioinformatics Elective", departments: ["BIO_INFORMATICS"], prereqs: ["BIO414"] },
  { code: "GEN305", name: "Quality Assurance", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
  { code: "BAS106", name: "Basics of English", credit_hours: 0, group_type: "Preparatory", departments: ["ALL"], prereqs: [] },
  { code: "BAS108", name: "Business Mathematics", credit_hours: 0, group_type: "Preparatory", departments: ["ALL"], prereqs: [] },
  { code: "AIMAI2", name: "x-lab", credit_hours: 0, group_type: "Elective", departments: ["AI_GENERAL", "CYBER_SECURITY", "BIO_INFORMATICS"], prereqs: [] },
  { code: "GEN103", name: "Professional Ethics", credit_hours: 2, group_type: "University Elective", departments: ["ALL"], prereqs: [] },
];
